# Generated by Django 3.2.12 on 2022-04-02 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('in_stock', models.PositiveIntegerField(default=0)),
                ('colors_available', models.CharField(default='', max_length=255)),
                ('sizes_available', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
                ('has_discount', models.BooleanField(default='')),
                ('discounted_percent', models.PositiveIntegerField(default=0)),
                ('is_new', models.BooleanField(default=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('sales_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
