# Generated by Django 3.2.12 on 2022-04-03 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='clothing', max_length=255),
        ),
    ]
